<div id="create_account">
  	<div id="tagline_account">&nbsp;</div>
    <div id="sidemenu_account2">&nbsp;</div>
    <div id="content_account">
	
	  <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	  <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
	
      <h3>Forgot your password?</h3>
      <p>Please enter your email address and click submit. </p>
      <p>We will send you an email containing a link to reset your password.</p>
      <p>&nbsp;</p>
      <div class="lable01">Your Email Address </div>
      <div class="field01">
	  <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" style="width:180px;" />
	  </div>

	  
      <br class="clr" />
      <p>&nbsp;</p>
      <p>
        <input type="submit" style="background-image:url(<?php echo $this->getSkinUrl('images/submit.gif') ?>); width:60px; height:20px;" value=""  />
      </p>
	  </form>
	<script type="text/javascript">
	//<![CDATA[
		var dataForm = new VarienForm('form-validate', true);
	//]]>
	</script>
      <p>&nbsp;</p>
      <h3 style="padding-left:150px;">OR</h3>
	  
	  
	  
	  <?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl().'customer/account/login/' ?>" method="post" id="login-form">
	  
      <h3>Try signing in again:</h3>
      <div class="lable01">Your Email Address</div>
      <div class="field01"><input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" style="width:180px;" /></div>
      <div class="lable01"> Your Password</div>
      <div class="field01"><input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>"  style="width:180px;" />
      </div>
      
      <br class="clr" />
      <p>&nbsp;</p>
      <p><input type="submit" style="background-image:url(<?php echo $this->getSkinUrl('images/login.gif') ?>); width:60px; height:20px;" value=""  />
      </p>
	    </form>
<script type="text/javascript">
//<![CDATA[
	var dataForm = new VarienForm('login-form', true);
//]]>
</script>
      <p>&nbsp;</p>
      <p>&nbsp;</p>
      <p>&nbsp;</p>
    </div>
  </div>