<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
  
  <!-- body container -->
<div id="headline" class="row">
  <h1>Sign in/Sign up</h1>
</div>
<div id="description" class="row">
  <p class="span12">Please Login Below. Not registered? Create your ICU account here: 
    <a class="" href="<?= $this->getCreateAccountUrl() ?>">Create Account</a></p>
</div>

<div id="login_panel" class="span6">
    <h3>Sign in</h3> 
    <p>For returning customers.</p>
    <form id="login-form" action="<?= $this->getPostActionUrl() ?>" method="post">
  	  <input  type="email" 
              id="email" 
              class="icu-input required-entry validate-email" 
              name="login[username]" 
              value="<?= $this->htmlEscape($this->getUsername()) ?>" 
              title="<?= $this->__('Email Address') ?>" 
              placeholder="Email Address"
            />
      <input  type="password" 
              id="pass" 
              class="required-entry validate-password" 
              name="login[password]" 
              title="<?= $this->__('Password') ?>"  
              placeholder="Password"
            />
      <input class="icu-btn" type="submit" value="Login"  />
    </form>
    <p>Forgot your password?  <a title="Click to retrieve password" href="<?= $this->getForgotPasswordUrl() ?>">Click Here</a></p>
      
  </div>

  <!-- /body container -->

<script type="text/javascript">
//<![CDATA[
	var dataForm = new VarienForm('login-form', true);
//]]>
</script>