<script type="text/javascript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
<?php echo $this->getBlockHtml('formkey')?>


<?php if($this->getIsSubscribed()) { ?>



<h3>My Mail</h3>
<p>You are subscribed to receive:</p>
<p>&nbsp;</p>
<p style="padding-left:20px;"><em>The ICU Newsletter</em></p>
<p style="padding-left:20px;"> Lucky you! Every week we deliver you the hottest news coming from Paris. </p>
<p style="padding-left:60px;">- New designer features</p>
<p style="padding-left:60px;">- Exclusive sales</p>
<p style="padding-left:60px;">- Paris art and fashion news</p>
<p style="padding-left:60px;">- Paris street style</p>
<p>&nbsp;</p>

<input type="checkbox" name="is_subscribed" id="subscription" value="0" title="<?php echo $this->__('General Subscription') ?>" class="checkbox" style="display:none;" />

<br class="clr" />
<p>
<input type="submit" style="background-image:url(<?php echo $this->getSkinUrl('images/btn-unsubcribe.gif') ?>); width:90px; height:20px;" value=""  />
</p>
<p>&nbsp;</p>
<p>&nbsp;</p>



<?php } else { ?>
<h3>My Mail</h3>
<p>You are not subscribed to the ICU Newsletter yet?! Well that&#39;s an easy fix.</p>
<p>&nbsp;</p>
<p> Every week we deliver you the hottest news coming from Paris.</p>
<p style="padding-left:40px;">- New designer features</p>
<p style="padding-left:40px;">- Exclusive sales</p>
<p style="padding-left:40px;">- Paris art and fashion news</p>
<p style="padding-left:40px;">- Paris street style</p>
<p>&nbsp;</p>
<div class="mail_box">
<div class="box01"><input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /></div>
<div class="box02">
  <h5>Sign me up to receive The ICU Newsletter <span style="font-size:13px;">(click <a href="#" style="color:#999999;" onclick="MM_openBrWindow('<?php echo $this->getUrl().'newsletter-sample.html' ?>','','scrollbars=yes,width=650,height=1900')">here</a> for sample newsletter)</span></h5>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
</div>
</div>


<br class="clr" />
<p>
<input type="submit" style="background-image:url(<?php echo $this->getSkinUrl('images/btn-subcribe.gif') ?>); width:80px; height:20px;" value=""  />
</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<?php } ?>


</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>