
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
<?php echo $this->getBlockHtml('formkey')?>


<?php if($this->getIsSubscribed()) { ?>

<h3>My Email Settings</h3>

<p>You are subscribed to receive:</p>
<p style="padding-left:20px;"><em>The ICU Newsletter</em></p>
<p style="padding-left:20px;"> Lucky you! Every week we deliver you the hottest news coming from Paris. </p>
	<ul>
		<li>- New designer features</li>
		<li>- Exclusive sales</li>
		<li>- Paris art and fashion news</li>
		<li>- Paris street style</li>
	</ul>

<input type="checkbox" name="is_subscribed" id="subscription" value="0" title="<?= $this->__('General Subscription') ?>" class="checkbox" style="display:none;" />

<input class="icu-btn" type="submit" value="Unsubscribe"  />



<?php } else { ?>
<h3>My Email Settings</h3>
<p>You are not subscribed to the ICU Newsletter yet?! Well that&#39;s an easy fix.</p>
<p> Every week we deliver you the hottest news coming from Paris.</p>
	<ul>
		<li>- New designer features</li>
		<li>- Exclusive sales</li>
		<li>- Paris art and fashion news</li>
		<li>- Paris street style</li>
	</ul>

<div>
	<input id="subscription" class="checkbox pull-left" type="checkbox" name="is_subscribed" value="1" title="<?= $this->__('General Subscription') ?>" checked="checked" />
  	<label for="subscription" class="span10">Sign me up to receive The ICU Newsletter</label>
</div>


<input class="icu-btn" type="submit" value="Subscribe"  />


<?php } ?>


</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>