

<div id="create_account">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
  	<div id="tagline_account">Create an account with ICU - In Paris</div>
    <div style="width:150px; float:left;">&nbsp;</div>
    <div id="content_account">
 <h3>Sign Up</h3> 
    <p>For New Customers. <span>Required Fields*</span></p>

        <input name="firstname" id="firstname" class="input-text required-entry" type="text"  />
        <input name="lastname" id="lastname" class="input-text required-entry" type="text"  />
        <input name="email" id="email_address" class="input-text validate-email required-entry"  type="email"  />
        <input id="password" class="input-text required-entry validate-password" name="password" type="password" />
        <input id="confirmation" name="confirmation" class="input-text required-entry validate-cpassword" type="password" />

      <p><input type="checkbox" class="checkbox" id="is_subscribed" value="1" title="Sign Up for Newsletter" name="is_subscribed"> Check to sign up for the ICU Newsletter  (click <a href="#" onclick="MM_openBrWindow('<?php echo $this->getUrl().'newsletter-sample.html' ?>','newsletter','scrollbars=yes,width=860,height=640')">here</a> for sample newsletter)</p>

	  <input class="icu-btn" type="submit" />

      <p><span>by clicking the &#8220;Submit&#8221; form above, you are agreeing to ICU&#8216;s 
	  <a href="#" onclick="MM_openBrWindow('<?php echo $this->getUrl().'terms-conditions.html' ?>','termsconditions','scrollbars=yes,width=720,height=460')">terms &amp; conditions</a>.</span></p>
      <p>&nbsp;</p>
      <p>&nbsp;</p>
    </div>
  </div>
  </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>