<div class="subscribe-left-block">
	<div class="subscribe-borders">
		<form action="<?php echo $this->getUrl('bfmsubscribe/subscriber/new') ?>" method="post" id="subscribe-left-validate-detail">
			<div class="subscribe-header">Subscribe to ICU</div>
			<div class="subscribe-content"><?= $this->__('Sign up for specials, promos and new product announcements from ICUinParis.com'); ?></div>
			<div class="newsletter-elements">
				<input type="email" 
				value="<?php echo $this->__('Your Email Address') ?>" 
				onfocus="if(this.value=='<?php echo $this->__('Your Email Address') ?>')this.value='';" 
				onblur="if(this.value=='')this.value='<?php echo $this->__('Your Email Address') ?>';" 
				name="email" id="newsletternew" 
				class="_for_sending" />
				<button class="subscribe-button" type="submit">
					<span>
						<img src="<?= $this->getSkinUrl('images/btn_arrow.gif') ?>" alt="Submit to ICU Newsletter" />
					</span>
				</button>
			</div>
		</form>
	</div>
</div>

<script type="text/javascript">
	//<![CDATA[
	var newsletterSubscriberFormDetail = new VarienForm('subscribe-left-validate-detail');
	//]]>
	jQuery(document).ready(function(){

		/* create static Newsletter  */
		bfm.utils.Newsletter.create("#subscribe-left-validate-detail");

	});
</script>
