<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php //echo $this->getChildHtml('head') ?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>ICU - IN PARIS [The Leading Online Boutique For Independent Design.]</title>
<link href="<?php echo $this->getSkinUrl('css/style.css') ?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->getSkinUrl('css/dropdown.css') ?>" media="all" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-1.4.2.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.jcarousel.min.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/skin3.css') ?>" />

<script type="text/javascript">

jQuery(document).ready(function() {
    jQuery('#mycarousel1').jcarousel({
        horizontal: true,
        scroll: 1,
		wrap: 'circular'
    });
});

</script>
<script type="text/javascript">

jQuery(document).ready(function() {
    jQuery('#mycarousel2').jcarousel({
        horizontal: true,
        scroll: 1,
		wrap: 'circular'
    });
});

</script>
</head>
<body>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
<!-- HEADER AND NAVIGATION SECTION -->
<?php echo $this->getChildHtml('header') ?>
<!-- /HEADER AND NAVIGATION SECTION -->
<div class="clr"></div>
<!-- BODY SECTION -->


<div id="body_section">
  <!-- body container -->

  	<div id="tagline_account">&nbsp;</div>
    
    <div id="sidemenu_account">
    <h5>My DashBoard</h5>
    	<?php echo $this->getChildHtml('left') ?>
    </div>
    
		<?php echo $this->getChildHtml('content') ?>
	  
  <!-- /body container -->
  <div class="clr"></div>
</div>





<!-- /BODY SECTION -->
<div class="clr"></div>
<!-- FOOTER SECTION -->
<?php echo $this->getChildHtml('footer') ?>
<!-- /FOOTER SECTION -->
<?php echo $this->getChildHtml('before_body_end') ?>
<div class="clr"></div>
</body>
</html>
