<?php
/**
 * Blue Fountain Media
 *
 * NOTICE OF LICENSE
 *
 * <notice_of_license>
 *
 * @category    BFM
 * @package     BFM_CanonicalUrl
 * @copyright   Copyright (c) 2011 Blue Fountain Media (http://www.bluefountainmedia.com/). All Rights Reserved.
 * @license     <license_url>
 */
$productUrl = $this->getHeadProductUrl();
if ($productUrl !== NULL):
?>
<link rel="canonical" href="<?php echo htmlspecialchars($this->getHeadProductUrl()) ?>" />
<?php endif; ?>