<script>
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<?php 
$theurl     = $this->helper('core/url')->getCurrentUrl();
$urlpieces  = explode("/", $theurl);

if($urlpieces[4] && $urlpieces[4] == "?success%2F="): ?>
<p class="note-msg">Your design has been submitted successfully.</p>
<?php endif; ?>


	<header id="submit_designs_header" class="container">
   	<h2 class="span10 offset2">Submit Your Design</h2>
    <p class="span8 offset2">We want to see you and depending on your creative outlet, you could be the next featured designer sold on I C U, or the subject for our next blog post, or even the next street style love for the day. Submit. You never know, you could be the next big inspiration... Click <a href="#" onclick="MM_openBrWindow('<?php echo $this->getUrl('').'more-design-info.html' ?>','termsconditions','scrollbars=yes,width=720,height=460')">HERE</a> for more info. </p>
</header>

<form id="design-submit-form" class="container" action="<?= $this->getUrl('designs/') ?>index/sendemail" method="post" enctype="multipart/form-data">
    
        
        <fieldset class="form_section row">
          <h4 class="one">Choose your outlet </h4>
          <div class="styled-select span3">
            <select name="outlet" id="outlet" class="required-entry span4">
              <option value="">Select</option>
              <option value="Accessory Designer">Accessory Designer</option>
              <option value="Blogger">Blogger</option>
              <option value="Clothing Designer">Clothing Designer</option>
              <option value="Graphic Designer">Graphic Designer</option>
              <option value="Jewelry Designer">Jewelry Designer</option>
              <option value="Illustrator">Illustrator</option>
              <option value="Photographer">Photographer</option>
            </select>
          </div>
        </fieldset>

        <fieldset class="form_section row">
          <h4 class="two">TELL US A LITTLE ABOUT YOU</h4>
          <div>
              <input name="name" id="name" class="required-entry span3" type="text" placeholder="Your Name" />
              <input name="compname" id="compname" class="span3" type="text" placeholder="Company Name/Design Alias/Blog" />            
              <input name="website" id="website" class="validate-clean-url span3" type="text" placeholder="Website" />
              <input name="email" id="email" class="required-entry validate-email span3" type="text" placeholder="Email" />
              <div class="styled-select span3">
                <select name="agerange" id="agerange" class="required-entry span4">
                    <option value="">Your age range</option>
            				<option value="18-">18-</option>
            				<option value="18-22">18-22</option>
            				<option value="22-26">22-26</option>
            				<option value="26-30">26-30</option>
            				<option value="30-35">30-35</option>
            				<option value="35+">35+</option>
                </select>
              </div>
          </div>
        </fieldset>

        <fieldset class="form_section row">
          <h4 class="three">TELL US ABOUT YOUR WORK</h4>
          <input name="yearfounded" id="yearfounded" type="text" class="span3" placeholder="Year founded" />
          <textarea name="yourbrand" id="yourbrand" class="span6" cols="" rows="" placeholder="Describe your brand (If applicable in 200 words or less)"></textarea>
          <textarea name="whatmade" id="whatmade" class="span6" cols="" rows="" placeholder="What made you want to start? (200 words or less)"></textarea>
          <input name="targetcustomer" id="targetcustomer" type="text" class="span3" placeholder="Who is your target customer?" />
    
          <label class="distro-channels">Current Distribution Channels</label>
          <label class="checkbox">
            <input name="channel1" id="channel1" type="checkbox" value="Small - Mid-size Boutiques" /> Small - Mid-size Boutiques</p>
          </label>
          <label class="checkbox">
            <input name="channel2" id="channel2" type="checkbox" value="Department Stores" />Department Stores
          </label>
          <label class="checkbox">
            <input name="channel3" id="channel3" type="checkbox" value="Online Boutiques" />Online Boutiques
          </label>
        </fieldset>

        <fieldset class="form_section row">
          <h4 class="four">Submit your work</h4>
          <textarea name="submission" id="submission" class="span6" cols="" rows="" placeholder="Describe your submission (500 words or less)"></textarea>
          <label>SUBMIT 5 IMAGES OF PRODUCT SAMPLES <span>(file size limit: 1MB/file)</span></label>
          <input type="file" name="p1" id="p1" size="60" class="span4" />
          <input type="file" name="p2" id="p2" size="60" class="span4" />
          <input type="file" name="p3" id="p3" size="60" class="span4" />
          <input type="file" name="p4" id="p4" size="60" class="span4" />
          <input type="file" name="p5" id="p5" size="60" class="span4" />
         
          <div class="lable03">         
            <p><input name="attest" id="attest" class="input-text required-entry" type="checkbox" value="I attest to all images/work uploaded is created &amp; owned by me." /> I attest to all images/work uploaded is <a href="#" onclick="MM_openBrWindow('<?php echo $this->getUrl('').'created-and-owned-by-me.html' ?>','termsconditions','scrollbars=yes,width=720,height=460')">created &amp; owned by me</a>. </p>
            
            <p><input name="agree" id="agree" type="checkbox" class="input-text required-entry" value="I agree to follow all formalities of the I C U Release Form" /> I agree to follow all formalities of the <a href="#" onclick="MM_openBrWindow('<?php echo $this->getUrl('').'icu-release-form.html' ?>','termsconditions','scrollbars=yes,width=720,height=460')">I C U Release Form</a>. </p>
          </div>
        </fieldset>
    
    	 <div class="row-fluid">
	      <input id="submit_design_btn" class="span6 offset3"  type="submit" value="Submit & Mercí"  />
      </div>
    </form>
<script>
//<![CDATA[
	var dataForm = new VarienForm('design-submit-form', true);
//]]>
</script>